name: Create GitHub Release

on:
  push:
    branches:
      - master

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Create GitHub Release
        uses: ./
        with:
          personal_access_token: ${{ secrets.PAT }}
          allowed_users: heitorpolidoroooo heitorpolidoro