name: Create Release

on:
  push:
    branches:
      - master

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
      - name: Teste
        uses: ./
        with:
          personal-access-token: ${{ secrets.PAT }}