name: Create Release

on:
  push:
    branches:
      - master

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: DEBUG
        run: ls -la

      - name: Teste
        uses: ./
        with:
          personal-access-token: ${{ secrets.PAT }}